apiVersion: apps/v1
kind: Deployment 
metadata:
  name: test-devco
spec:
  selector:
    matchLabels:
      app: test-devco
  replicas: 2 
  template:
    metadata:
      labels:
        app: test-devco
    spec:
      containers:
        - name: imagen-prueba
          image: salomoneslait/prueba-devco:imagen-prueba
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-devco
spec:
  type: LoadBalancer
  selector:
    app: test-devco
  ports:
  - name: http
    port: 80
    targetPort: 3000