apiVersion: v1
kind: Namespace
metadata:
  name: pruebadevco

---

apiVersion: apps/v1
kind: Deployment 
metadata:
  name: test-devco
  namespace: pruebadevco
spec:
  selector:
    matchLabels:
      app: test-devco
  replicas: 2 
  template:
    metadata:
      labels:
        app: test-devco
    spec:
      containers:
        - name: imagen-prueba
          image: salomoneslait/prueba-devco:imagen-prueba
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 10001
            readOnlyRootFilesystem: true
            capabilities:
              drop:
               - NET_RAW
               - ALL
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-devco
  namespace: pruebadevco
spec:
  type: LoadBalancer
  selector:
    app: test-devco
  ports:
  - name: http
    port: 80
    targetPort: 3000