# pipeline CI/CD 

name: 'Terraform'

on:
  push:
    branches:
      - main  
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: 1.3.9
                
      - name: terraform init
        id: init
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=devco-state" \
            -backend-config="key=infra.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true"
    
        
